In [1]:
import torch

# Tensors

In [13]:
# 5x3 matrix, uninitialized
x = torch.empty(5, 3)
x

tensor([[ 0.0000e+00, -1.0842e-19, -1.0657e-08],
        [ 8.5920e+09,  8.4078e-45,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00, -1.0842e-19,  0.0000e+00]])

In [14]:
# randomly initialized matrix
x = torch.rand(5, 3)
x

tensor([[ 0.5474,  0.3682,  0.7561],
        [ 0.4678,  0.6800,  0.7191],
        [ 0.0614,  0.3912,  0.2252],
        [ 0.2673,  0.9054,  0.1096],
        [ 0.2336,  0.4228,  0.7517]])

In [15]:
# matrix of zeros, dtype long
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])

In [18]:
# construct tensor directly from data
x = torch.tensor([5.5, 3])
x

tensor([ 5.5000,  3.0000])

In [22]:
# create tensor with existing tensor, reuse properties like dtype
x = x.new_ones(5, 3, dtype=torch.double)
print(x)
x = torch.rand_like(x, dtype=torch.float)
print(x)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)
tensor([[ 0.3561,  0.1837,  0.8547],
        [ 0.4510,  0.2848,  0.0420],
        [ 0.3106,  0.9101,  0.2719],
        [ 0.9390,  0.6972,  0.4598],
        [ 0.5491,  0.3375,  0.0859]])


In [23]:
# get size
x.size()

torch.Size([5, 3])

# Operations

In [24]:
# addition syntax 1
y = torch.rand(5, 3)
x+y

tensor([[ 0.7353,  0.8975,  1.5121],
        [ 0.8992,  0.2929,  0.3848],
        [ 0.3624,  1.1797,  0.3247],
        [ 1.3990,  0.7517,  0.9865],
        [ 0.8500,  0.8220,  0.9611]])

In [25]:
# addition syntax 2
torch.add(x, y)

tensor([[ 0.7353,  0.8975,  1.5121],
        [ 0.8992,  0.2929,  0.3848],
        [ 0.3624,  1.1797,  0.3247],
        [ 1.3990,  0.7517,  0.9865],
        [ 0.8500,  0.8220,  0.9611]])

In [26]:
# addition: output tensor as arg
result = torch.empty(5, 3)
torch.add(x, y, out=result)
result

tensor([[ 0.7353,  0.8975,  1.5121],
        [ 0.8992,  0.2929,  0.3848],
        [ 0.3624,  1.1797,  0.3247],
        [ 1.3990,  0.7517,  0.9865],
        [ 0.8500,  0.8220,  0.9611]])

In [27]:
# in-place addition (all in-place tensor ops have postfix _)
y.add_(x)
y

tensor([[ 0.7353,  0.8975,  1.5121],
        [ 0.8992,  0.2929,  0.3848],
        [ 0.3624,  1.1797,  0.3247],
        [ 1.3990,  0.7517,  0.9865],
        [ 0.8500,  0.8220,  0.9611]])

In [28]:
# indexing
x[:, 1]

tensor([ 0.1837,  0.2848,  0.9101,  0.6972,  0.3375])

In [29]:
# resizing
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [30]:
# get val of single element tensor
x = torch.randn(1)
print(x, x.item())

tensor([-0.7561]) -0.7560533881187439


# NumPy Bridge

In [32]:
# Torch tensor to NumPy array
a = torch.ones(5)
b = a.numpy()
print(a, b)

tensor([ 1.,  1.,  1.,  1.,  1.]) [1. 1. 1. 1. 1.]


In [33]:
# b is still linked to a as numpy version
a.add_(1)
print(a, b)

tensor([ 2.,  2.,  2.,  2.,  2.]) [2. 2. 2. 2. 2.]


In [37]:
# numpy array to torch tensor, still linked as before
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a, b)

[2. 2. 2. 2. 2.] tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)


CUDA tensors  
Tensors can be moved onto any device using the .to method.

In [38]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!